### PR TITLE
.travis.yml: Update Clippy to use a more recent nightly (2018-06-18)

### PR DESCRIPTION
**Pull request by ErichDonGubler**

### CODE REVIEW

**Comment by CAD97** [comment]
You need to update the rustc version being used for the clippy job as well.

**Comment by ErichDonGubler** [comment]
...there! How's that? :)

**Comment by CAD97** [comment]
Looks like rustfmt got an update in that range to not use `--write-format` anymore...

**Comment by ErichDonGubler** [comment]
@CAD97: Should I switch this to use `--emit`, then?

**Comment by CAD97** [comment]
Yeah that'd be great it's basically part of this upgrade

**Comment by CAD97** [comment]
bors: r+

Thanks for this! I'm planning an update to the post with probably too many helper bots once the 2018 edition and/or stable clippy comes around.

**Pull request merged**
