### PR TITLE
Use the stable `clippy` and `rustfmt` components

### PR DESCRIPTION
**Pull request by ErichDonGubler**

### CODE REVIEW

**Comment by ErichDonGubler** [comment]
@CAD97: Just wanted to ping you here in case this got lost in your inbox. :)

**Comment by matthias-t** [comment]
hasn't the component name changed to just "clippy"?

**Comment by ErichDonGubler** [comment]
@matthias-t: That's true, I filed this PR when things were still in preview. I'll amend it once I have more than mobile access!

**Comment by matthias-t** [comment]
rustfmt-preview has also changed to just rustfmt

**Comment by ErichDonGubler** [comment]
Updated.

**Comment by CAD97** [comment]
Yep, this got a bit lost. Looks good!

bors: r+

**Pull request merged**
